% GSA code v1.1.
% Generated by Esmat Rashedi, 2010.
% "	E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
% �GSA: A Gravitational Search Algorithm�, Information sciences, vol. 179,
% no. 13, pp. 2232-2248, 2009."
%
% Main function for using GSA algorithm.
clear all;clc
%  inputs:
% N:  Number of agents.
% max_it: Maximum number of iterations (T).
% ElitistCheck: If ElitistCheck=1, algorithm runs with eq.21 and if =0, runs with eq.9.
% Rpower: power of 'R' in eq.7.
% F_index: The index of the test function. See tables 1,2,3 of the mentioned article.
%          Insert your own objective function with a new F_index in 'test_functions.m'
%          and 'test_functions_range.m'.
%  outputs:
% Fbest: Best result.
% Lbest: Best solution. The location of Fbest in search space.
% BestChart: The best so far Chart over iterations.
% MeanChart: The average fitnesses Chart over iterations.

 N=50;
 max_it=100;
 ElitistCheck=1; Rpower=1;
 min_flag=1; % 1: minimization, 0: maximization

 F_index=1
 [Fbest,Lbest,BestChart,MeanChart]=GSA(F_index,N,max_it,ElitistCheck,min_flag,Rpower);
 Fbest
 Lbest


 % #############  Resolvendo o FP para conferência do caso ótimo  ######################
 define_constants
 mpc= loadcase('case14');
 mpc.bus(1, VM) = Lbest(1);
    mpc.gen(1, VG) = Lbest(1);

    mpc.bus(2, VM) = Lbest(2);
    mpc.gen(2, VG) = Lbest(2);

    mpc.bus(3, VM) = Lbest(3);
    mpc.gen(3, VG) = Lbest(3);

    mpc.bus(6, VM) = Lbest(4);
    mpc.gen(4, VG) = Lbest(4);

    mpc.bus(8, VM) = Lbest(5);
    mpc.gen(5, VG) = Lbest(5);

    mpc.branch(8,BR_STATUS) = Lbest(6); %tap 4-7
    mpc.branch(9,BR_STATUS) = Lbest(7); %tap 4-9
    mpc.branch(10,BR_STATUS) = Lbest(8); %tap 5-6

    mpc.bus(9,BS)=Lbest(9);

    results = runpf(mpc);

 semilogy(BestChart,'--k');
 title(['\fontsize{12}\bf F',num2str(F_index)]);
 xlabel('\fontsize{12}\bf Iteration');ylabel('\fontsize{12}\bf Best-so-far');
 legend('\fontsize{10}\bf GSA',1);

